### ISSUE TITLE
Indices too big

### ISSUE THREAD

**Issue by SidneyLan** [tensorflow/gnn#258]
Below error occors when training, and too many indices are bigger than 1000, but the indices are all smaller than 200 when construct the graph tensor. Why the indices in an adjacency can be changed? Would any one please advise any possible reason? Thanks.

graph_tensor_ops.py, line 109, in broadcast_node_to_edges
      return tf.gather(node_value, adjacency[node_tag])
Node: 'model_2/graph_update/node_set_update_1/multi_head_attention_conv/GatherV2_6'
indices[77] = 387 is not in [0, 384)
[[{{node model_2/graph_update/node_set_update_1/multi_head_attention_conv/GatherV2_6}}]] [Op:__inference_train_function_20223]

**Comment by phanein** [comment]
Hi @SidneyLan,

A couple thoughts:

- [Merging a batch of inputs into components of one graph](https://github.com/tensorflow/gnn/blob/9d96add45a54a257cdcf769bb735a0e38780de20/tensorflow_gnn/docs/guide/input_pipeline.md#merging-a-batch-of-inputs-into-components-of-one-graph) this part of the docs describes how multiple graph tensors are combined in a batch (into one big graph tensor).  This could be the index changing phenomenon you're referring to.
- Your root error might be due to malformed input.  I would double check to make sure there aren't any unexpectedly missing input features (for example).

There isn't enough here to truly debug, however if you provide a minimum working example we might have more thoughts.

Hope that helps!

**Comment by SidneyLan** [comment]
Hi @phanein, 
  Thanks for your guide, but I still can't fix this issue. Could please run my reproducer and check? Thank you very much!
You can unzip it to your home folder and run etl.py and reproduce the issue.
[tf-gnn.zip](https://github.com/tensorflow/gnn/files/10253416/tf-gnn.zip)

**Comment by SidneyLan** [comment]
Could help to take a look? Thanks.
