### ISSUE TITLE
Supported dtypes?

### ISSUE THREAD

**Issue by DiTo97** [tensorflow/gnn#281]
Hi,

I was wondering if there was somewhere a list of all the dtypes that TF-GNN currently supports.

Not long ago, I read a quite in-depth [guide](https://towardsdatascience.com/tensorflow-gnn-an-end-to-end-guide-for-graph-neural-networks-a66bfd237c8c) on your package where the author reported that only "int32", "float32" and "string" are supported. If that's the case, I was wondering why, and if there are any scheduled plans to support more dtypes in the future.

I think having more dtypes would be valuable not to waste precious resources. For example, in the sample task depicted in the guide, the author had to represent (boolean) friendship edges with "int32" wasting 31 poor bits

**Comment by phanein** [comment]
Hi @DiTo97,

Interesting question, (and we do care about those poor bits).   I would say that we already support different dtypes, but it does depend on how one uses them.

For instance, in the article you linked there's two concepts I would like to disambiguate:

- For node or edge features, the dtypes are generally limited by what can be stored inside a [tf.train.Example](https://www.tensorflow.org/tutorials/load_data/tfrecord#tftrainexample).  However if one really is interested at efficiency at this level, after deserializing I think smaller dtypes can be coerced.  I'd need to see some exact errors to understand what's going on.

- `tfgnn.Adjacency.from_indices`.  The arguments to this must be more than one bit each since they take the node ids (integers) to create the relationships.  Supporting `int16` for tiny graphs might allow a potential speedup.
