### ISSUE TITLE
Question about classification of paths in a graph

### ISSUE THREAD

**Issue by quoter** [tensorflow/gnn#287]
Hi,

I want to build a model that would classify paths in a graph. My current idea is to store in the GraphSchema context sequences of nodes indices with labels, then in the readout stage extract hidden edge features by these indices into a new sequence and then process that sequence with some Recurrent or Attention layer.

I wonder, would this idea work? My concern is that graph merging procedure that is made in batching would make indices invalid.

**Comment by phanein** [comment]
Hi @quoter,

Interesting question! (and sorry about the delay in responding).  We actually just added some functionality that will really help in situations like these, where the readout varies per example.

Instead of using context features (which can be problematic with indexing, as you mention), our solution is actually to introduce a edge set specifically for readout.  This allows ultimate flexibility for composing readouts of links, paths, etc.  One final message passing operation over the model then composes the readout parameters to the desired shapes.

The documentation is not completely updated for this yet, but you can find some relevant API functions in commit #328
